trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'd1851293-d098-42b3-8a67-f4ef80f67176'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    clean: true
    msbuildArchitecture: 'x64'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    runInParallel: true
    codeCoverageEnabled: true
    testRunTitle: 'ReactiveElements test'