trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: NuGetCommand@2
  displayName: Restore NuGets
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'ReactiveElements/nuget.config'

- task: VSBuild@1
  displayName: Clean and build solution
  inputs:
    solution: '**\*.sln'
    clean: true
    msbuildArchitecture: 'x64'